version: '3.4'

networks:
  default:
    name: care

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - ./docker/.prebuilt.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis/redis-stack-server:6.2.6-v10
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6380:6379"

  localstack:
    image: localstack/localstack:latest
    restart: unless-stopped
    environment:
      - AWS_DEFAULT_REGION=ap-south-1
      - EDGE_PORT=4566
      - SERVICES=s3
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - EXTRA_CORS_ALLOWED_HEADERS=*
      - DEBUG=1
    volumes:
      - "${TEMPDIR:-./care/media/localstack}:/var/lib/localstack"
      - "./docker/awslocal:/etc/localstack/init/ready.d/"
    ports:
      - "4566:4566"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    restart: unless-stopped
    volumes:
      - azurite-data:/data
    ports:
      - 10000:10000 # Blob service
    environment:
      - DEBUG=azurite:*
      - AZURITE_ACCOUNTS=devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
    command: azurite-blob --blobHost 127.0.0.1 --blobPort 10000 --debug path/debug.log --loose

  fidelius:
    image: khavinshankar/fidelius:latest
    restart: unless-stopped
    ports:
      - "8092:8090"

volumes:
  postgres-data:
  redis-data:
  azurite-data:
