# Generated by Django 5.1.4 on 2025-09-19 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOdooAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_agent_id', models.IntegerField(help_text='The ID of the agent in Odoo system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The Care user associated with this Odoo agent', on_delete=django.db.models.deletion.CASCADE, related_name='odoo_agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Odoo Agent',
                'verbose_name_plural': 'User Odoo Agents',
                'db_table': 'odoo_user_odoo_agent',
            },
        ),
    ]
