# Generated by Django 5.1.4 on 2025-07-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0480_merge_20250521_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='invoice_number_expression',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
