# Generated by Django 5.1.4 on 2025-08-19 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0031_rename_reason_for_visit_tokenbooking_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeitem',
            name='commission_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_charge_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
