# Generated by Django 5.1.4 on 2025-09-05 19:15

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0049_chargeitemdefinitioncategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeitemdefinitioncategory',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chargeitemdefinitioncategory',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chargeitemdefinitioncategory',
            name='level_cache',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chargeitemdefinitioncategory',
            name='parent_cache',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='chargeitemdefinitioncategory',
            name='root_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root', to='emr.chargeitemdefinitioncategory'),
        ),
        migrations.AlterField(
            model_name='chargeitemdefinitioncategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='emr.chargeitemdefinitioncategory'),
        ),
    ]
