# Generated by Django 5.1.4 on 2025-09-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0050_chargeitemdefinitioncategory_has_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreconciliation',
            name='is_credit_note',
            field=models.BooleanField(default=False),
        ),
    ]
