# Generated by Django 5.1.4 on 2025-07-09 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0098_invoice_number_alter_invoice_title'),
        ('facility', '0481_facility_invoice_number_expression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='facility',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='facility.facility'),
            preserve_default=False,
        ),
    ]
